# $Id: Makefile,v 1.1.1.1 2005/03/24 06:16:15 arch-linux Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

obj-y := init.o console.o printf.o  misc.o
#bootstr.o init.o misc.o segment.o console.o printf.o
