# $Id: Makefile,v 1.1.1.1 2005/03/24 06:16:30 arch-linux Exp $
# Makefile for the Sun Boot PROM interface library under
# Linux.
#

EXTRA_AFLAGS := -ansi
EXTRA_CFLAGS := -Werror

lib-y   := bootstr.o devops.o init.o memory.o misc.o \
	   tree.o console.o printf.o p1275.o map.o cif.o
